name: crew-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyyaml
  - pandas
  - ipython
  - pydantic
  - python-dotenv
  - pip:
    - crewai
    - typing-extensions
    - openai
